-- Hala Talab Admin Stage 8
-- جداول إدارة مستقلة + سياسات تمنح الوصول فقط لمن هو موجود في admin_users.

create table if not exists public.admin_commission_rules (
  id uuid primary key default gen_random_uuid(),
  store_id uuid references public.stores(id) on delete cascade,
  commission_type text not null default 'percent' check (commission_type in ('percent','fixed')),
  commission_value numeric not null default 0 check (commission_value >= 0),
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_subscriptions (
  id uuid primary key default gen_random_uuid(),
  store_id uuid not null references public.stores(id) on delete cascade,
  plan_name text not null default 'شهري',
  amount numeric not null default 0 check (amount >= 0),
  status text not null default 'active' check (status in ('active','paused','expired')),
  starts_at date,
  ends_at date,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_system_settings (
  setting_key text primary key,
  setting_value text not null default '',
  updated_by uuid references auth.users(id) on delete set null,
  updated_at timestamptz not null default now()
);

create table if not exists public.admin_audit_log (
  id bigint generated by default as identity primary key,
  admin_id uuid references auth.users(id) on delete set null,
  action text not null,
  entity_type text,
  entity_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

alter table public.admin_commission_rules enable row level security;
alter table public.admin_subscriptions enable row level security;
alter table public.admin_system_settings enable row level security;
alter table public.admin_audit_log enable row level security;

-- Helper predicate: authenticated user is an enabled admin.
create or replace function public.is_hala_admin()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (
    select 1 from public.admin_users a
    where a.id = auth.uid() and a.role = 'admin' and coalesce(a.is_active,true) = true
  );
$$;
revoke all on function public.is_hala_admin() from public;
grant execute on function public.is_hala_admin() to authenticated;

-- Admin-owned tables: full CRUD for admins only.
do $$
declare t text; p text;
begin
  foreach t in array array['admin_commission_rules','admin_subscriptions','admin_system_settings','admin_audit_log'] loop
    for p in select policyname from pg_policies where schemaname='public' and tablename=t loop
      execute format('drop policy if exists %I on public.%I',p,t);
    end loop;
    execute format('create policy %I on public.%I for all to authenticated using (public.is_hala_admin()) with check (public.is_hala_admin())','admin_full_access_'||t,t);
  end loop;
end $$;

-- Read-only visibility for real system tables when they exist.
do $$
declare t text; p text;
begin
  foreach t in array array['store_categories','coupons','store_promotions','promotions','customer_support_conversations','customer_support_messages'] loop
    if to_regclass('public.'||t) is not null then
      for p in select policyname from pg_policies where schemaname='public' and tablename=t and policyname='admin_stage8_read' loop
        execute format('drop policy if exists %I on public.%I',p,t);
      end loop;
      execute format('create policy admin_stage8_read on public.%I for select to authenticated using (public.is_hala_admin())',t);
    end if;
  end loop;
end $$;

-- Seed safe defaults only in the new admin settings table.
insert into public.admin_system_settings(setting_key,setting_value)
values ('platform_name','هلا طلب'),('currency','IQD'),('driver_active_order_limit','10'),('maintenance_mode','false'),('maintenance_message','')
on conflict (setting_key) do nothing;
